### ISSUE TITLE
Wrong Member Given As Inviter

### ISSUE THREAD

**Issue by MrReacher** [cyrus01337/invites#1]
## What Were You Trying To Do?
I am using a slightly modified version of this cog: Removed some methods and listeners, made it to only work on a specific guild.
Here is what I'm using: https://hastebin.com/wetaginajo.py

## What Is The Problem?
Wrong member given as inviter.

## How Did You Come Across This?
![1](https://reacher.dedsec.dev/Ze1QoF.png)
![2](https://reacher.dedsec.dev/FFUeDs.png)
![3](https://reacher.dedsec.dev/pVL6yg.png)

## What Version Of Discord.py Do You Have?
1.5.1 all intents except presences

**Comment by cyrus01337** [comment]
I'm not really too sure as to why this is happening. I think I might need a bit more information:

- Did 2 people join at near enough the same time?
- Did the person have a name change around that time?

Do you have any ideas @XuaTheGrate ?

**Comment by MrReacher** [comment]
No to both questions. The tracker works fine for a few member joins (can't tell how many), but then the behavior changes and I get wrong data.

**Comment by cyrus01337** [comment]
Can you please repost your code in [Mystbin](https://mystb.in/)? Xua only now received the mention and is having trouble viewing the original code.

**Comment by MrReacher** [comment]
Sure thing: https://mystb.in/CanImmediateRiders.python
I applied one of your changes to how you compare the old invites to the new invites and it seems that is working as intended for now. (L107 in mystbin) I'll keep an eye out if it happens again. In the future, what information should I provide to make your debugging something easier?

**Comment by MrReacher** [comment]
Confirmed that it's still not fixed.

**Comment by ZingyAwesome** [comment]
I also had this issue.

**Comment by mysistersbrother** [comment]
Did the user `EDU#1353` also create an invite but this invite was not the one used to join the guild?

**Comment by MrReacher** [comment]
> Did the user `EDU#1353` also create an invite but this invite was not the one used to join the guild?

No, that user _had_ a permanent invite from ages ago, but did not create one recently.
EDIT: And yes, as you can see from the last two images, that was the invite used to join.

**Comment by MrReacher** [comment]
Nice catch, @mysistersbrother!

Using this code: https://mystb.in/EnemiesBernardGuild.python
I've got this: https://pastebin.com/f95QXFHR (I know it's pastebin and not a beautiful bin service but I have a good reason for that)

As you can see from the logs (line 18), one invite is missing. The explanation is in #2. `on_invite_delete` doesn't get fired when an invite expires.
