### ISSUE TITLE
Event Not Firing Sometimes

### ISSUE THREAD

**Issue by ZingyAwesome** [cyrus01337/invites#7]
## What Were You Trying To Do?
I invited my alt using a newly generated link. The invite update event never fired. This has happened a few times before. I rejoined the server with my alt and the event still did not fire.

## What Is The Problem?
The on_invite_update does not fire sometimes.

## How Did You Come Across This?
1. Generate a new invite link
2. Invite somebody
3. The invite_update event may not fire

## What Version Of Discord.py Do You Have?
> 1.6 with all intents enabled

**Comment by cyrus01337** [comment]
Could you please submit a code snippet?

**Comment by ZingyAwesome** [comment]
```
    @commands.Cog.listener()
    async def on_invite_update(self, member, invite):
        await self.bot.wait_for_invites()
        print(f"{member} joined with invite {invite} by {invite.inviter}")
```
The problem only happens with very freshly generated invites.

**Comment by mysistersbrother** [comment]
> ```
>     @commands.Cog.listener()
>     async def on_invite_update(self, member, invite):
>         await self.bot.wait_for_invites()
>         print(f"{member} joined with invite {invite} by {invite.inviter}")
> ```
> 
> The problem only happens with very freshly generated invites.

What invite "settings" are you using? eg. invite expiry time, invite usages

And what poll period are you using for the `update_invite_expiry` task.

**Comment by ZingyAwesome** [comment]
Doesn't happen anymore after I modified it a bit
