### ISSUE TITLE
CPU Usage Issue

### ISSUE THREAD

**Issue by ZingyAwesome** [cyrus01337/invites#8]
## What Were You Trying To Do?
I noticed that after the update to fix expiring invites, this cog now spikes the cpu to 100% whenever it is active. 

## What Is The Problem?
The cpu spikes to 100% CPU for as long as the cog is loaded. When I unload it, the CPU usage falls back to normal values. This only happens on linux for some reason and I have no idea why. I am guessing there is some inefficiency in the code.

## How Did You Come Across This?
1. Load the cog
2. CPU spikes to 100%
3. Unload the cog
4. CPU usage normalises 

## What Version Of Discord.py Do You Have?
> 1.6 with all intents

**Comment by ZingyAwesome** [comment]
It seems to be related to the delete_expired task.

**Comment by mysistersbrother** [comment]
> It seems to be related to the delete_expired task.

what findings have you made that made you think that? 
also what changes have you made to the cog?

**Comment by ZingyAwesome** [comment]
After changing the delete_expired from a task loop to a coroutine that I invoke with create_task, the CPU usage returns back to normal.

**Comment by mysistersbrother** [comment]
> After changing the delete_expired from a task loop to a coroutine that I invoke with create_task, the CPU usage returns back to normal.

That's strange. Is this behaviour consistent?
And have you made any edits to the cog before this behaviour?

**Comment by ZingyAwesome** [comment]
No modifications before this except removing a few comments and the invites command.
Not always consistent. Very rarely the CPU usage will drop back to normal for a minute or two before coming back up to 100.

**Comment by mysistersbrother** [comment]
> No modifications before this except removing a few comments and the invites command.
> Not always consistent. Very rarely the CPU usage will drop back to normal for a minute or two before coming back up to 100.

May you please post the complete cog with all modifications in mystbin and sent it here.

Could anyone else possibly test this and see if they are experiencing the same issue, unfortunately I am unable to because my computer has been having internet problems recently and I am unable to use it for this purpose.

**Comment by cyrus01337** [comment]
Virtually no change on my end, having a high guild count could be the issue due to mass fetching maybe. Otherwise, nothing I know of could possibly cause this.
