### ISSUE TITLE
Vanity URL

### ISSUE THREAD

**Issue by ZingyAwesome** [cyrus01337/invites#9]
## What Is The Problem?
When someone joins with a vanity URL the event is not triggered

## How Did You Come Across This?
Get an alt, join with a vanity url and the event will not trigger

## What Version Of Discord.py Do You Have?
> 1.6

**Comment by cyrus01337** [comment]
Invites does not store vanity invites, I will make sure it supports this.

**Comment by cyrus01337** [comment]
While the implementation is able to be created, this is unable to be tested as all main contributors harbour insufficient ~~equipment~~ environments for testing such a feature.

**Comment by ZingyAwesome** [comment]
Will this be added or not?

**Comment by cyrus01337** [comment]
It has and has not been - the feature in question has been implemented, however, it lays dormant in the [vanity branch](https://github.com/cyrus01337/invites/tree/vanity) until it has been tested and any existing/known bugs are squashed.

**Comment by ZingyAwesome** [comment]
I have been able to test this on a server with a vanity invite and it works well without issues.
